environment: development
language: en-US # used in head <html class="no-js" lang="{{ site.language }}">
title: Bloocks fastest websites generator ever!
description: Build badass and fastest marketing websites with Bloocks, a static websites generator to build Ecommerce and websites on top of tecnical performaces.
logo_name: <span class="ml-3 font-extrabold text-xl text-white px-1 py-1 bg-gradient-to-tr from-indigo-400 to-indigo-500">Bloocks</span>
domain_name: bloocks.dev # you need to place this in your package.json file in the
name: Bloocks
url: "https://antoniotrento.github.io/bloocks-test"
logo: "img/main-logo.png"
logocaption: Bloocks a static site generator of the new era
seologo: "img/main-logo.png" # must be at least 112x112 for seo purposes
footer-logo: "/img/boom-logo-80.png"
footer-slogan: "Build your next awesome app with bloocks"
stickymenu: 'true'
iconclass: 'flex-shrink-0 h-6 w-6 text-indigo-600'
fontawesomecolor: '#4F46E5' # You can use hex, rgb and rgba example: rgba(51, 51, 51, 0.9)
# iconclass-old: 'h-8 mr-4 text-indigo-600 duration-150 cursor-pointer transition-color hover:text-gray-600'
cdn_url: https://cdn.jsdelivr.net/gh/antoniotrento/bloocks-test@gh-pages/

collections:
  staff_members:
    _hide_content: true
    _icon: account_circle
  products:
    _hide_content: true
    output: true
    _icon: shopping_cart
  posts-airtable:
    output: true
    source: posts-airtable.json
    id_key: id
    layout: posts-airtable-page
  post-en-template:
    output: true
    source: post-en-template.json
    id_key: id
    layout: post-en-airtable-page
  2testpost:
    output: true
    source: 2testpost.json
    id_key: id
    layout: 2testpost

# https://github.com/danklammer/jekyll-airtable_data don't work with leatest versions of jekyll and create problem with jekyll-picture-tag-plugin
#airtable_data:
#  api_key: keyi3xqM42QQD1Alt # Airtable API key available in the API documentation for your base
#  app_id: appnwOceWdxueLDIl # Airtable app ID found in the API documentation for your base
#  tables:
#    - post-en-template
#    - posts-airtable
#    - post-test
#    - 2testpost
#    #- [Your Airtable Table Name 3]

# for Jekyll SEO tag plugin and for using information into the project code structure
# Usage at https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md

author :
  name : Antonio Trento
  firstname: Antonio
  lastname: Trento
  email : lantoniotrento@gmail.com
  github : bloocks/bloocks.github.io
  twitter : lantoniotrento
  facebook: lantoniotrento
  linkedin: antoniotrento
  instagram: lantoniotrento
  pinterest: lantoniotrento

locale: en_US


## Call to actions menu, link and text. All the menus are placed into _data/menus.yml file

cta:
  ctamenu: 'Learn Now' # 'I&#39;m in!' for special characters use ASCII codes with &# after 'code_num' https://theasciicode.com.ar/ascii-printable-characters/braces-curly-brackets-opening-ascii-code-123.html
  ctamenulink: '/subscribe'
  ctamenuclass: 'ml-8 whitespace-nowrap inline-flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-indigo-600 hover:bg-indigo-700'
  mobilectamenuclass: 'w-full flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-indigo-600 hover:bg-indigo-700'
  icon: heroicons/outline/finger-print
  iconclass: flex-shrink-0 h-6 w-6 text-grey-100
  animation: ping
  animationclass: animate-ping ease duration-300
  animicon: heroicons/outline/finger-print
  animicoclass: flex-shrink-0 h-6 w-6 text-grey-100
  menuextra: 'Terms'
  descmenuextra: 'Discover bloocks'
  menuextralink: '/terms-and-conditions'
  menuextraclass: 'md:hidden lg:flex xl:flex 2xl:flex'
  extraicon: heroicons/outline/scale
  extraiconclass: flex-shrink-0 h-6 w-6 text-grey-400

# The custom bloock data in _includes/partials/subscribe-base.html

subscribe:
  cta: <span class="block">Ready to build faster?</span><span class="block text-indigo-600">Stay updated, we will lauch soon.</span>
  ctabutton: Get updates
  ctabtnlink: /subscribe
  extabutton: Dicover the roadmap
  extrabtnlink: /roadmap
  background: bg-gradient-to-b from-gray-100 to-white

aside:
  headline: Discover Bloocks
  description: Learn what is bloocks and be updated about this tool
  image: /bloocks-prelaunch.jpg
  typecta1: linkbutton
  contentcta1: Became a part of Bloocks
  hrefcta1: /subscribe
  iconcta1: heroicons/outline/finger-print
  iconclasscta1: flex-shrink-0 h-6 w-6 text-grey-100
  animationcta1:
  sizingcta1:
  typographycta1:
  colorcta1:
  classcta1:
  otherclasscta1:
  stylecta1:
  targetcta1:
  relcta1:
  propertiescta1:

# Google recaptcha v2 invisible site key from https://www.google.com/recaptcha/about/ used for contact form --> https://developers.google.com/recaptcha/docs/v3
# To use recaptcha correctly you need to create a serverless function to verify the submitter: here how bloocks handle this: https://medium.com/codait/protecting-your-website-forms-with-serverless-captcha-27e3ed2794a0
recaptcha: '6LeJjSMaAAAAAJGFHYES4HuEr77fA2jn1Pt3Oxq_'

# Config ibm cloud action for recaptcha verification
# bx wsk package update bloocks --param CAPTCHA_SECRET "API-SECRET" --param SUCCESS_URL "https://antoniotrento.github.io/bloocks-test/thank-you-formcake/" --param FAILURE_URL "https://antoniotrento.github.io/bloocks-test/fail-submit/"
# bx wsk action update "bloocks/contactus" --kind nodejs:10 contactus.js --web true
# bx wsk action get "bloocks/contactus" --url

ibmcloud:
  action: 'https://eu-gb.functions.appdomain.cloud/api/v1/web/lantoniotrento%40gmail.com_dev/bloocks/contactus'

# Using an heroku app to validate recaptcha fomrs by: https://github.com/andrewrmn/invisible-recaptcha-validator

heroku:
  action: 'https://bloocksrecaptcha.herokuapp.com/'


# Contact form, it use aplinejs to send json data to the action link via a POST request I use Formcake form: https://formcake.com

contactform:
  action: 'https://api.formcake.com/api/form/d3e56666-0d67-4303-90d1-54cd52e0b242/submission'
  redirect: 'https://antoniotrento.github.io/bloocks-test/thank-you-formcake/'
  error: 'https://antoniotrento.github.io/bloocks-test/thank-you-error/'
  title: 'Contact Bloocks team'
  subtitle: 'Write down your questions or helpfull information to improve this project.'
  name: 'Your name'
  email: 'Your email'
  message: 'Write your message below'
  button: 'Send Message'
  policy: 'Yes, I consent to my data being stored according to the guidelines set out in the <a class="font-bold" href="/terms-and-conditions/" target="blank">Terms and conditions</a>.'
  footer: 'Bloocks is in prelaunch, the project is under heavy development. This form use <a class="font-bold" href="https://formcake.com" target="blank" rel="noopener noreferrer nofollow">Formcake</a> as a service.'

# Sendinblue API (do not make it public ex. do not use if you are using github pages with public repository)

sendinblue:
  api: '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'
  listid: '[6]'
  emailtemplateid: '11'
  redirectionurl: 'https://antoniotrento.github.io/bloocks-test/confirmation/'
  firstredirect: 'https://antoniotrento.github.io/bloocks-test/thank-you-formcake/'
  error: 'https://antoniotrento.github.io/bloocks-test/thank-you-error/'
  action: 'https://api.sendinblue.com/v3/contacts/doubleOptinConfirmation'
  title: 'Contact Bloocks team'
  subtitle: 'Write down your questions or helpfull information to improve this project.'
  name: 'Your name'
  email: 'Your email'
  button: 'Send Message'
  footer: 'I agree to receive your newsletters and accept the <a class="font-extrabold" href="/terms-and-conditions/">data privacy statement</a>.'

# google_site_verification: 1234

webmaster_verifications:
  # google: 1234
  # bing: 1234
  # alexa: 1234
  # yandex: 1234
  # baidu: 1234

social:
  name: Antonio Trento
  links:
    - https://twitter.com/lantoniotrento
    - https://www.facebook.com/lantoniotrento
    - https://www.linkedin.com/in/antoniotrento
    - https://github.com/antoniotrento
    - https://keybase.io/antoniotrento
# twitter website account
twitter:
  username: lantoniotrento
  card: summary_large_image
facebook:
  page: https://www.facebook.com/lantoniotrento

# facebook:
 # app_id: 12345 #the app id from https://developers.facebook.com/
 # admins: 12345 #the page ID from https://www.facebook.com/pg/lantoniotrento (page-link), left click about scroll down and find 'Page ID'
 # publisher: 12345 #the page ID from https://www.facebook.com/pg/lantoniotrento (page-link), left click about scroll down and find 'Page ID'
 # pixel: 12345


 #END CONFIG for Jekyll SEO tag plugin

## Coockie consent and analytics

# internalconsent: true

### Analytics and coockie consent using tagmanager and osano coockie consent
#### More info to config at: https://connect.act-on.com/hc/en-us/articles/360023758034-Integrating-a-Tag-Manager-and-Cookie-Consent-Provider
google :
  tagmanager_id: 'GTM-TZFDWZR' #id di google tag manager
#  ad_client: 'ca-pub-9204963049240271' # id google ADsense used for configuring the adsense account will be cookie compilant ready by tagmanager configurations
#  for adsense implementation I follow this https://www.analyticsmania.com/post/how-to-install-google-adsense-with-google-tag-manager-gdpr-ready/ whit the help of this https://connect.act-on.com/hc/en-us/articles/360023758034-Integrating-a-Tag-Manager-and-Cookie-Consent-Provider
#  tracking_id : 'G-QSWTLSSE28' # Id google analitics (not usefull in this configuration)
#  amp_tracking_id: 'UA-184034920-1' # AMP usage is deprecated is not compatible with noone coockie solution
#  optimize_id : 'GTM-NF68992' #I'id di google optimize per A/B Testing
#  optimize_experiment_id: ' ' #I'id di dell'esperimento google optimize per A/B Testing
#  amp_tagmanager_id: 'GTM-PD8KN8K' # AMP usage is deprecated is not compatible with noone coockie solution
#  ads_conversion_id: '' # id google ads_conversion_id
#  double_click_id: '' id google double_click

# Coockie consent by quantcast https://www.quantcast.com/products/choice-consent-management-platform/

# quantcast: # Deprecated. Prefer google tag manager for more elasticity and config possibilities quantcast seem not supported in amp version
#   qcode: ''
#   qucode: ''
#   email: ''


# bloocks

# Menu

## Colors And typografy

### Primary colors

### Fonts color

### Globals

## Single Block Proprieties

# bloocks elements Sizes

# Text size

# Payment options
## Payment plugin

# Ecommerce

stripe:
  public: pk_test_us1JnQw8qH6W3BToMzl1oeDW00rx8lXKTc
  success_url: test # namespace (for translated page) of the redirect page
  fail_url: test

snipcart:
  api: YWFiZDYzMzYtZjY3MC00ZDliLTgwNWUtMGFlY2IyOWQ0Y2Q2NjM2NDcxMTc3NTMxNjE4MDUw
# fullpage_cart: true

# default-currency: usd

## Payment plugin


# This instruction that use http://jch.penibelst.de/ tech is used to delete all HTML comments and minify all HTML

compress_html:
  comments: ["<!--  ", "  -->"]

## jekyll-responsive-image https://github.com/wildlyinaccurate/jekyll-responsive-image need to have template file into _includes/ folder no upfolders or downfolders

#responsive_image:
#  template: _includes/srcset-resized-fallback.html
#  sizes:
#    - width: 1800
#    - width: 1200
#    - width: 800
#    - width: 480
#    - width: 320
#  base_path: img
#  output_path_format: img/resized/%{width}/%{basename}
# comments using google forms and sheets https://jdvp.medium.com/using-google-forms-for-jekyll-comments-e84d7a01237b
comment-post: https://docs.google.com/forms/d/e/1FAIpQLSfqMJAlPlOzPVJq_uycDzPoLZHfxC-g4dVHdIZ4wGqtvT8K7w
comment-read: https://docs.google.com/spreadsheets/d/1cYnFgMhPM3CRVBsHjXuWykm0gPCA8F5oz3u0AdpwzwI
comment-post-fields: [ entry.843871588, entry.1138360390, entry.1914105834 ]

review-post: https://docs.google.com/forms/d/e/1FAIpQLScCtwQBIEn0TuNxRDUXhI8e2MiHiGF8p6b7kjdNpyvxDbQogw
review-read: https://docs.google.com/spreadsheets/d/1KWYts1s1F0w3Yy-HwFuFgKab0I1qJIktf3bDQsv_DBk
review-post-fields: [ entry.1959616308, entry.1244667124, entry.856767572, entry.1223756939 ]

## Jekyll picture tag https://rbuchberger.github.io/jekyll_picture_tag/
picture:
  source: "img"
  output: "img"
  suppress_warnings: true
  ignore_missing_images: true
  fast_build: true
  relative_url: false
  baseurl_key: baseurl_root
  cdn_url: https://cdn.statically.io/img/antoniotrento.github.io/bloocks-test/

# This command below can be uncomment when you have the image files uploaded
# to your online repository to be able to serve your images from statically CDN
# (remember to upload the images only in the img folder and subfolders and on first commit the images to the server folder otherwise it will not work)

# cdn_url: https://cdn.statically.io/img/bloocks.github.io/
# cdn_url: https://cdn.jsdelivr.net/gh/bloocks/bloocks.github.io@master/docs/
## Jekyll picture tag presets are in _data/picture.yml file from examples https://rbuchberger.github.io/jekyll_picture_tag/users/presets/examples.html

## don't works in leatest version of jekyll jekyll-imagemagick plugin for Jekyll picture tag https://rdoc.info/gems/jekyll-imagemagick

imagemagick:
  enabled: true
  widths:
    - 1024
    - 512
    - 0
  input_directories:
    - img
  input_formats:
    - ".png"
    - ".tiff"
  output_formats:
    jpg: "-quality 93% -define jpeg:dct-method=float -strip -interlace Plane"
    webp: "-quality 100%"

# From https://github.com/jekyllresources/jekyll-cloudinary
cloudinary:
  cloud_name: antoniotrento
  origin_url: https://res.cloudinary.com/antoniotrento/image/upload/
  verbose: true
  presets:
    default:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: "(min-width: 50rem) 50rem, 90vw"
      attributes:
        loading: "lazy"
    onethird:
      min_width: 110
      max_width: 535
      fallback_max_width: 300
      steps: 3
      sizes: "(min-width: 50rem) 17rem, 30vw"
      attributes:
        class: "one3rd"
        loading: "lazy"
    logo:
      min_width: 80
      max_width: 400
      fallback_max_width: 200
      steps: 3
      sizes: '(min-width: 50rem) 13rem, (min-width: 40rem) 25vw, 45vw'
      figure: never
      attributes:
        class: logo
    figure:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: '(min-width: 50rem) 50rem, 90vw'
      figure: always
    grayscale:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: "(min-width: 50rem) 50rem, 90vw"
      effect: grayscale
      format: webp
      quality: 39
      attributes:
        loading: "lazy"


defaults:
  - scope:
      path: ""
    values:
      image: /img/default-card.png
  - scope:
      path: ""
      type: "products"
    values:
      layout: "product"
      is-product: true
# Jekyll Admin create problems during the script npm run start, brosersync can't reload the site and give me an error and exit from the serving loop made in gulpfile.babel.js

# jekyll_admin:
#   hidden_links:
#     - posts
#     - pages
#     - staticfiles
#     - datafiles
#     - configuration

# Multilang plugin settings --> https://github.com/kurtsson/jekyll-multiple-languages-plugin
## Have some problem in implementation derived by jekyll-seo-tag-plugin and the menu logic from jekyll-menu plugin
### See to do list in README.md file for more info

languages: ["en", "it", "fr", "de"]
exclude_from_localizations: ["assets", "CNAME", "css", "js", "favicon.ico", "robots.txt", "sitemap_index.xml"]
defaultLang: en
languageNames:
  it: Italiano
  en: English
  fr: Francais
  de: Deutsche


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Permalinks for improve SEO keywords in blog posts
baseurl: ""
permalink: /:title/

# This will require each of these plugins automatically.
plugins:
  #- jekyll-airtable_data
  - pagemaster
  - jekyll-multiple-languages-plugin # https://github.com/kurtsson/jekyll-multiple-languages-plugin
  - jekyll-cloudinary # https://github.com/nhoizey/jekyll-cloudinary
  - jekyll_picture_tag # https://rbuchberger.github.io/jekyll_picture_tag/
  - jekyll-target-blank # https://github.com/keithmifsud/jekyll-target-blank
  - jekyll-seo-tag # https://github.com/jekyll/jekyll-seo-tag
  - jekyll-menus # https://github.com/dojekyll/jekyll-menus

#  - jekyll-sitemap
#  - jekyll-responsive-image # https://github.com/wildlyinaccurate/jekyll-responsive-image

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js
  - netlify.toml
  - postcss.config.json
  - postcss.config.js
  - build.js
  - docs
